# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=200)),
                ('issue_id', models.CharField(max_length=200)),
                ('error_code', models.CharField(max_length=200)),
                ('config_id', models.CharField(max_length=200)),
                ('software_label', models.CharField(max_length=200)),
                ('tc_number', models.CharField(max_length=200)),
                ('suite', models.CharField(max_length=200)),
                ('script_lebel', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('jenkins_path', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('env_version', models.CharField(max_length=100)),
            ],
        ),
    ]
