# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='fault_area',
            field=models.CharField(choices=[('CI Fault', 'CI Fault'), ('Product Fault', 'Product Fault')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='error',
            name='state',
            field=models.CharField(choices=[('in progress', 'in progress'), ('frozen', 'frozen'), ('solved', 'solved')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='error',
            name='test_environment',
            field=models.CharField(choices=[('ufte', 'ufte'), ('hibiscus', 'hibiscus')], default='', max_length=200),
        ),
    ]
