# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0002_auto_20160905_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='script_lebel',
            new_name='script_label',
        ),
    ]
