# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0003_auto_20160905_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='error',
            name='fault_area',
            field=models.CharField(choices=[('CI Fault', 'CI Fault'), ('Product Fault', 'Product Fault')], max_length=200),
        ),
        migrations.AlterField(
            model_name='error',
            name='state',
            field=models.CharField(choices=[('in progress', 'in progress'), ('frozen', 'frozen'), ('solved', 'solved')], max_length=200),
        ),
        migrations.AlterField(
            model_name='error',
            name='test_environment',
            field=models.CharField(choices=[('ufte', 'ufte'), ('hibiscus', 'hibiscus')], max_length=200),
        ),
    ]
