# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('errors', '0004_auto_20160920_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='error',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
